apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: prometheus-kafka-exporter
      release: kafka-exporter
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: exporter-port
      path: /metrics
      interval: 30s